In [1]:
import argparse
import os
import tensorflow as tf
from dataset import Dataset
#try:
#    from dataset import Dataset
#except:
#    from flyai.dataset import Dataset

import bert.modeling as modeling
from bert import tokenization
from model import Model
from path import MODEL_PATH
# 超参
parser = argparse.ArgumentParser()
parser.add_argument("-e", "--EPOCHS", default=20, type=int, help="train epochs")
parser.add_argument("-b", "--BATCH", default=16, type=int, help="batch size")
args = parser.parse_args([])

# 数据获取辅助类
dataset = Dataset()
# 模型操作辅助类
modelpp = Model(dataset)

-f


In [8]:
bert_config

In [2]:
from pytorch_pretrained_bert import BertAdam

In [11]:
from pytorch_pretrained_bert import tokenization

In [14]:
import os
from path import DATA_PATH

In [15]:
bert_vocab_file = os.path.join(DATA_PATH, "model", "uncased_L-12_H-768_A-12", 'vocab.txt')

In [17]:
tokenizer = BertTokenizer.from_pretrained(bert_vocab_file)

INFO:pytorch_pretrained_bert.tokenization:loading vocabulary file data/input/model/uncased_L-12_H-768_A-12/vocab.txt


In [22]:
tokenizer.tokenize("Who was Jim Henson")

['who', 'was', 'jim', 'henson']

In [19]:
from bert.run_classifier import convert_single_example_simple

In [21]:
convert_single_example_simple(max_seq_length=20,tokenizer=tokenizer,text_a="Who was Jim Henson ?",text_b="Jim Henson was a puppeteer .")

([101,
  2040,
  2001,
  3958,
  27227,
  1029,
  102,
  3958,
  27227,
  2001,
  1037,
  13997,
  11510,
  1012,
  102,
  0,
  0,
  0,
  0,
  0],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [3]:
import torch
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM,BertForSequenceClassification

# OPTIONAL: if you want to have more information on what's happening, activate the logger as follows
import logging
logging.basicConfig(level=logging.INFO)

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenized input
text = "[CLS] Who was Jim Henson ? [SEP] Jim Henson was a puppeteer [SEP]"
tokenized_text = tokenizer.tokenize(text)

# Mask a token that we will try to predict back with `BertForMaskedLM`
masked_index = 8
tokenized_text[masked_index] = '[MASK]'
assert tokenized_text == ['[CLS]', 'who', 'was', 'jim', 'henson', '?', '[SEP]', 'jim', '[MASK]', 'was', 'a', 'puppet', '##eer', '[SEP]']

# Convert token to vocabulary indices
indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
# Define sentence A and B indices associated to 1st and 2nd sentences (see paper)
segments_ids = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1]

# Convert inputs to PyTorch tensors
tokens_tensor = torch.tensor([indexed_tokens])
segments_tensors = torch.tensor([segments_ids])

INFO:pytorch_pretrained_bert.tokenization:loading vocabulary file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased-vocab.txt from cache at /home/changebio/.pytorch_pretrained_bert/26bc1ad6c0ac742e9b52263248f6d0f00068293b33709fae12320c0e35ccfbbb.542ce4285a40d23a559526243235df47c5f75c197f04f37d1a0c124c32c9a084


In [3]:
tokens_tensor

tensor([[  101,  2040,  2001,  3958, 27227,  1029,   102,  3958,   103,  2001,
          1037, 13997, 11510,   102]])

In [34]:
?BertForSequenceClassification

In [4]:
# Load pre-trained model (weights)
model = BertForSequenceClassification.from_pretrained('bert-base-uncased',num_labels=2)
#model.eval()

INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/changebio/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
INFO:pytorch_pretrained_bert.modeling:extracting archive file /home/changebio/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpwo0zirhg
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

INFO:pytorch_pretrained_bert.modeling:Weights of Ber

In [5]:
model.to('cuda')

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): BertLayerNorm()
      (dropout): Dropout(p=0.1)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): BertLayerNorm()
              (dropout): Dropout(p=0.1)
            )
          )
          (intermediat

In [4]:
# If you have a GPU, put everything on cuda
tokens_tensor = tokens_tensor.to('cuda')
segments_tensors = segments_tensors.to('cuda')
model.to('cuda')

# Predict hidden states features for each layer
with torch.no_grad():
    encoded_layers, _ = model(tokens_tensor, segments_tensors)
# We have a hidden states for each of the 12 layers in model bert-base-uncased
assert len(encoded_layers) == 12

INFO:pytorch_pretrained_bert.modeling:loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/changebio/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
INFO:pytorch_pretrained_bert.modeling:extracting archive file /home/changebio/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmpgng_gme3
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

INFO:pytorch_pretrained_bert.modeling:Weights of Ber

ValueError: not enough values to unpack (expected 2, got 1)

In [6]:
x_train, y_train, x_test, y_test = dataset.next_batch(args.BATCH)
x_input_ids = x_train[0]
x_input_mask = x_train[1]
x_segment_ids = x_train[2]

In [23]:
?BertAdam

In [8]:
from torch import nn

In [27]:
?loss_fn

In [29]:
from torch.optim import Adam

In [10]:
model.train()
optimizer = BertAdam(model.parameters(), lr=1e-4, weight_decay=1e-4)
loss_fn = nn.CrossEntropyLoss()  
for i in range(args.EPOCHS):
    x_train, y_train, x_test, y_test = dataset.next_batch(args.BATCH)
    x_input_ids = x_train[0]
    x_input_mask = x_train[1]
    x_segment_ids = x_train[2]

    x_input_ids=torch.from_numpy(x_input_ids).to('cuda')
    x_input_mask=torch.from_numpy(x_input_mask).to('cuda')
    x_segment_ids = torch.from_numpy(x_segment_ids).to('cuda')
    y_train = torch.from_numpy(y_train).to('cuda')

    outputs = model(x_input_ids,x_segment_ids,x_input_mask)
    optimizer.zero_grad()

    loss = loss_fn(outputs, y_train)
    loss.backward()
    print(loss)
    optimizer.step()

tensor(0.4690, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4785, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4030, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4726, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.1654, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.2517, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4269, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.6581, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.6490, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4570, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.5563, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.1525, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.2573, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.3967, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.4833, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.5050, device='cuda:0', grad_fn=<NllLossBackward>)
tensor(0.3555, device='cuda:0', grad_fn=<NllLossBackward

In [19]:
y_train

tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0]], device='cuda:0')

In [20]:
p = model(x_input_ids,x_segment_ids,x_input_mask)

In [21]:
p

tensor([[0.7883, 0.8513],
        [0.7983, 0.8764],
        [0.7920, 0.8793],
        [0.7923, 0.8668],
        [0.7876, 0.8553],
        [0.7869, 0.8356],
        [0.7892, 0.8561],
        [0.7823, 0.8503],
        [0.7957, 0.8578],
        [0.7893, 0.8246],
        [0.7733, 0.7679],
        [0.7848, 0.8335],
        [0.7898, 0.8627],
        [0.7845, 0.7867],
        [0.7998, 0.8682],
        [0.7880, 0.8257]], device='cuda:0', grad_fn=<AddmmBackward>)

In [24]:
path = modelpp.get_remote_date("https://test.flyai.com/m/uncased_L-12_H-768_A-12.zip")
print('bret_path', path)

lr = 0.0006  # 学习率
# 配置文件
data_root = os.path.splitext(path)[0]
bert_config_file = os.path.join(data_root, 'bert_config.json')
bert_config = modeling.BertConfig.from_json_file(bert_config_file)
init_checkpoint = os.path.join(data_root, 'bert_model.ckpt')
bert_vocab_file = os.path.join(data_root, 'vocab.txt')
token = tokenization.CharTokenizer(vocab_file=bert_vocab_file)

input_ids = tf.placeholder(tf.int32, shape=[None, None], name='input_ids')
input_mask = tf.placeholder(tf.int32, shape=[None, None], name='input_masks')
segment_ids = tf.placeholder(tf.int32, shape=[None, None], name='segment_ids')
input_y = tf.placeholder(tf.float32, shape=[None, 1], name="input_y")
weights = {
    'out': tf.Variable(tf.random_normal([768, 1]))
}
biases = {
    'out': tf.Variable(tf.constant(0.1, shape=[1, ]))
}

model = modeling.BertModel(
    config=bert_config,
    is_training=False,
    input_ids=input_ids,
    input_mask=input_mask,
    token_type_ids=segment_ids,
    use_one_hot_embeddings=False)

tvars = tf.trainable_variables()
(assignment, initialized_variable_names) = modeling.get_assignment_map_from_checkpoint(tvars, init_checkpoint)
tf.train.init_from_checkpoint(init_checkpoint, assignment)
output_layer_pooled = model.get_pooled_output()  # 这个获取句子的output

w_out = weights['out']
b_out = biases['out']
pred = tf.add(tf.matmul(output_layer_pooled, w_out), b_out, name="pre1")
pred = tf.reshape(pred, shape=[-1, 1], name="pre")

loss = tf.reduce_mean(tf.square(tf.reshape(pred, [-1]) - tf.reshape(input_y, [-1])))
#
train_op = tf.train.AdamOptimizer(lr).minimize(loss)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(args.EPOCHS):
        x_train, y_train, x_test, y_test = dataset.next_batch(args.BATCH)
        x_input_ids = x_train[0]
        x_input_mask = x_train[1]
        x_segment_ids = x_train[2]
        loss_, _ = sess.run([loss, train_op],
                            feed_dict={input_ids: x_input_ids, input_mask: x_input_mask, segment_ids: x_segment_ids,
                                       input_y: y_train})
        print('loss:', loss_)

    modelpp.save_model(sess, MODEL_PATH, overwrite=True)


Model download succeeded !
bret_path data/input/model/uncased_L-12_H-768_A-12.zip
loss: 30.050611
loss: 47327.93
loss: 536.47925
loss: 47685.582
loss: 10079.994
loss: 5027.6685
loss: 26.975506
loss: 1975.286
loss: 254.80496
loss: 570.1449
loss: 1455.8423
loss: 583.6741
loss: 8.960073
loss: 613.5812
loss: 828.2617
loss: 258.0138
loss: 13.890854
loss: 383.17657
loss: 534.7079
loss: 208.96922
INFO:tensorflow:No assets to save.


INFO:tensorflow:No assets to save.


INFO:tensorflow:No assets to write.


INFO:tensorflow:No assets to write.


INFO:tensorflow:SavedModel written to: data/output/model/best/saved_model.pb


INFO:tensorflow:SavedModel written to: data/output/model/best/saved_model.pb


In [6]:
dataset.get_all_processor_data()[0]

[array([[ 101, 1940,  100, ...,    0,    0,    0],
        [ 101, 1855,  100, ...,    0,    0,    0],
        [ 101, 1855,  100, ...,    0,    0,    0],
        ...,
        [ 101, 1855,  100, ...,    0,    0,    0],
        [ 101, 1855, 1916, ...,    0,    0,    0],
        [ 101,  100,  100, ...,    0,    0,    0]]),
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])]

In [5]:
[i.shape for i in dataset.get_all_processor_data()[0]]

[(100, 256), (100, 256), (100, 256)]

In [13]:
from lstm.processor import load_data

trn,val = load_data()

trn

{'id': 'ATEC', 'type': 'csv', 'config': {'train_url': 'https://dataset.flyai.com/dataset/ATEC/dev.zip', 'test_url': 'https://dataset.flyai.com/dataset/ATEC/dev.zip'}}
[200.0, 26183.07, 16734.344824600794, 153.0, 11378.25, 24999.0, 36142.75, 62669.0]
[200.0, 0.11, 0.3136749269530403, 0.0, 0.0, 0.0, 0.0, 1.0]
不要冻结我的花呗                                   2
另一个支付宝花呗关了，新的支付宝能开通花呗吗                     2
临时花呗额度参加分期吗                                2
收钱码能向用户收花呗付款吗                              2
花呗额度可以转到银行卡里面吗                             2
今天花呗付款，没有鼓励金                               2
借呗还有多少                                     2
花呗能寄快递吗                                    2
我开通了，，信用卡和花呗的，什么到现在怎么还没有通过，申请到现在怎么还没有通过    2
花呗的钱想提前还上怎么弄                               2
Name: texta, dtype: int64
负的额度还可以用花呗支付吗    2
没有找到花呗怎么办        2
花呗分期付款，只能用一次吗    2
用了花呗的钱怎还呀        2
花呗付款也没有奖励金       2
借呗切换网商贷          2
花呗可以关了自动还款吗      2
开通花呗不用有什么费用      2
我说花呗里么么有钱        2
我还要还几个月的花呗款      2
Name: textb, dtype: int64

id                                       texta  \
0   11367                              花呗额度可以转到银行卡里面吗   
1   33911                                    我只有花呗里有钱   
2   10747                               我用花呗直接付款可以分期吗   
3     717                                   花呗需要手机验证吗   
4   19226           要还花呗，可是退款的钱还没退回花呗，如果我还了花呗退回的钱去哪儿了   
5   62669                       蚂蚁花呗只能***至***号选择分期付款吗   
6   22129                 当月***号当天用的花呗，还款日是不是下月***号前了   
7   34394  蚂蚁借呗里边就是借出来的钱，就是我在余额宝里有钱，它会自动扣除吗，就是每个月还的时候   
8    2238                               我那收钱码不支持花呗付款吗   
9    2191                                    花呗自动帮我买了   
10  47648                                      借呗还有多少   
11  51262                                     花呗是货到付款   
12   4227                              花呗的临时额度，可以分期还吗   
13   1384                               收钱码能向用户收花呗付款吗   
14  26020                                 什么时候可以分期换花呗   
15  35573                               支付宝pc端怎么找不到花呗   
16  30508                                使用花呗收款吗钱会到哪里   
17  33519                                  花呗显示关联另一账户   
18  22189                               今天用的花呗 什么时候还钱   
19  23863                               花呗逾期还最低还款还能用吗   
20  57883                         选择的商品支持花呗分期，我为什么不能付   
21   7902                                  支付宝付款可以花呗吗   
22  19994                                我***月份还了多少花呗   
23  16690                                今天花呗付款，没有鼓励金   
24  20722                              还款日过了，为什么花呗不能用   
25  18215                       商家退到花呗，我也早就还过款了，商家退的钱   
26  32830                                  借呗活跃度是什么意思   
27  33074                                     花呗不用利息吧   
28  52848                                     花呗能寄快递吗   
29   9370                                    花呗分期申请发票   
..    ...                                         ...   
70  16046                               蚂蚁花呗分期中还能在分期吗   
71  24504                           我十一月十号不是还清蚂蚁借呗的款吗   
72  29207                           花呗可以扫描商家支付宝二维码付款吗   
73  54330                     我想分期买个笔记本电脑，但是花呗额度不足怎么办   
74    153                                 我不想用不用的用花呗的   
75  16935                                花呗的钱想提前还上怎么弄   
76  39323                             我现在还多少钱可以恢复使用花呗   
77   1155                                 蚂蚁花呗怎么看还款日期   
78  49254                                    不要冻结我的花呗   
79   6551                               花呗还最低，影响个人信用吗   
80  12896                           蚂蚁借呗借***个月可以提前还款吗   
81  47825                                   在哪兑换花呗分期卷   
82   8888                               蚂蚁借呗未还清还可以再借么   
83  11238                                在花呗买东西在哪查看物流   
84  27100                        我用了花呗里的钱咋还款，银行卡可不可以扣   
85   7578                                     花呗开开通不了   
86  20167                                 怎么显示不了借呗金额了   
87  10351                             花呗账单分期怎么看到是买什么么   
88   5116                          开通过花呗账户之后关闭了如何再次开通   
89  47197                      另一个支付宝花呗关了，新的支付宝能开通花呗吗   
90  29793                     我是这个月***日借呗***万，分***个月还   
91  55893                               借呗额度用完可以调整额度吗   
92  27150                                   借呗什么时候能恢复   
93  37312                                如何分期还花呗的临时额度   
94  31559                         花呗手机号不是我得，也有可能是我以前的   
95    297                                   花呗可以跨店使用吗   
96  25494                                 密付付款方可以用花呗吗   
97  32734     我开通了，，信用卡和花呗的，什么到现在怎么还没有通过，申请到现在怎么还没有通过   
98   7583                                   我的借呗怎么没放款   
99  29401                                    那怎么样使用花呗   

                                       textb  label  
0                             账户余额里的钱可以还给花呗吗      0  
1                                  我说花呗里么么有钱      0  
2                               我要花呗分期还款有利息吗      0  
3                                ***的花呗要验证码嘛      0  
4     他这个款又退回到花呗了，我这个钱已经还了呀，现在是什么情况，这钱到底去哪里了      0  
5                              花呗分期付款，只能用一次吗      1  
6                   今天是花呗还款日，如果今天购买是不是需要今天还款      0  
7   蚂蚁借呗借的钱明天就到还款日了，可现在转不钱进余额宝，蚂蚁借呗会自动从储

In [16]:
import jieba

In [19]:
x_ids = [list(jieba.cut(str(trn.iloc[i,1]))) for i in range(len(trn))]

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.496 seconds.
Prefix dict has been built succesfully.


In [29]:
y_ids = [list(jieba.cut(str(trn.iloc[i,2]))) for i in range(len(trn))]

In [22]:
import numpy as np

In [32]:
xlen_95 = int(np.percentile([len(o) for o in x_ids], 99))
ylen_95 = int(np.percentile([len(o) for o in y_ids], 99))

In [33]:
xlen_95,ylen_95

(27, 28)

In [39]:
np.log(66988)/np.log(14993)

1.1556814709667682

In [15]:
#from create_dict import load_dict

def load_dict(file=None):
    char_dict_re = dict()
    if file==None:
        dict_path = os.path.join(DATA_PATH, 'word.dict')
    else:
        dict_path = os.path.join(DATA_PATH, file)
    with open(dict_path, encoding='utf-8') as fin:
        char_dict = json.load(fin)
    char_dict["_bos_"] = 0
    char_dict["_pad_"] = 1
    char_dict["_eos_"] = 2
    char_dict["_unk_"] = 3
    for k, v in char_dict.items():
        char_dict_re[v] = k
    return char_dict, char_dict_re

stoi_dict,itos_dict  = load_dict(file="words.dict")

In [2]:
dataset.get_all_processor_data()

([array([[ 101, 1940,  100, ...,    0,    0,    0],
         [ 101, 1855,  100, ...,    0,    0,    0],
         [ 101, 1855,  100, ...,    0,    0,    0],
         ...,
         [ 101, 1855,  100, ...,    0,    0,    0],
         [ 101, 1855, 1916, ...,    0,    0,    0],
         [ 101,  100,  100, ...,    0,    0,    0]]),
  array([[1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         ...,
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 0, 0, 0]]),
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])],
 array([[0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0

In [3]:
import json

In [5]:
from path import DATA_PATH

In [7]:
embedding_path = os.path.join(DATA_PATH, 'embedding.json')
with open(embedding_path, encoding='utf-8') as f:
    vocab = json.loads(f.read())

In [9]:
len(vocab['能减'])

200

In [1]:
from processor import load_data
trn,val = load_data()
trn

ImportError: cannot import name 'load_data'